/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/dnetcgui.h>
#include <proto/dnetcgui.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
    struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
    struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
    struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

    return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
    return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
    return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static ULONG stub_dnetcguiOpenPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct DnetcIFace *Self = (struct DnetcIFace *) ExtLib->MainIFace;

	return Self->dnetcguiOpen(
		(ULONG)regarray[0],
		(UBYTE *)regarray[8],
		(struct WBArg *)regarray[9],
		(const char *)regarray[10]
	);
}
STATIC CONST struct EmuTrap stub_dnetcguiOpen = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_dnetcguiOpenPPC };

static BOOL stub_dnetcguiClosePPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct DnetcIFace *Self = (struct DnetcIFace *) ExtLib->MainIFace;

	return Self->dnetcguiClose(
		(struct ClientGUIParams *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_dnetcguiClose = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_dnetcguiClosePPC };

static ULONG stub_dnetcguiHandleMsgsPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct DnetcIFace *Self = (struct DnetcIFace *) ExtLib->MainIFace;

	return Self->dnetcguiHandleMsgs(
		(ULONG)regarray[0]
	);
}
STATIC CONST struct EmuTrap stub_dnetcguiHandleMsgs = { TRAPINST, TRAPTYPE, (uint32 (*)(uint32 *))stub_dnetcguiHandleMsgsPPC };

static VOID stub_dnetcguiConsoleOutPPC(uint32 *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((uint32)Base + Base->lib_PosSize);
	struct DnetcIFace *Self = (struct DnetcIFace *) ExtLib->MainIFace;

	Self->dnetcguiConsoleOut(
		(ULONG)regarray[0],
		(UBYTE *)regarray[8],
		(BOOL)convert_int16(regarray[1])
	);
}
STATIC CONST struct EmuTrap stub_dnetcguiConsoleOut = { TRAPINST, TRAPTYPENR, (uint32 (*)(uint32 *))stub_dnetcguiConsoleOutPPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_dnetcguiOpen,
	&stub_dnetcguiClose,
	&stub_dnetcguiHandleMsgs,
	&stub_dnetcguiConsoleOut,
	(CONST_APTR)-1
};
